version: '3.8'

services:
    dev-backend-service:
        container_name: prod-backend-service
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        ports:
            - "8000:8000"
