export enum Subject {
	USER = 'USER',
	GENERIC_TOKEN = 'GENERIC_TOKEN',
	SNEAKER = 'SNEAKER',
	BRAND = 'BRAND',
	FAVOURITE = 'FAVOURITE',
	SNEAKER_IMAGE = 'SNEAKER_IMAGE',
	CATEGORY = 'CATEGORY',
	SNEAKER_SIZE = 'SNEAKER_SIZE'
}