/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * thecube
 * Platform API
 * OpenAPI spec version: 1.0.0
 */

export type MixedClassColour = typeof MixedClassColour[keyof typeof MixedClassColour];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MixedClassColour = {
  Red: 'Red',
  Green: 'Green',
  Blue: 'Blue',
  White: 'White',
  Black: 'Black',
  Yellow: 'Yellow',
  Orange: 'Orange',
  Grey: 'Grey',
} as const;
