/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * thecube
 * Platform API
 * OpenAPI spec version: 1.0.0
 */

export type SneakerSize = typeof SneakerSize[keyof typeof SneakerSize];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SneakerSize = {
  NUMBER_5: '5',
  '55': '5.5',
  NUMBER_6: '6',
  '65': '6.5',
  NUMBER_7: '7',
  '75': '7.5',
  NUMBER_8: '8',
  '85': '8.5',
  NUMBER_9: '9',
  '95': '9.5',
  NUMBER_10: '10',
  '105': '10.5',
} as const;
