/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * thecube
 * Platform API
 * OpenAPI spec version: 1.0.0
 */
import type { SneakerImageEntityCreatedAt } from './sneakerImageEntityCreatedAt';
import type { SneakerImageEntityDeletedAt } from './sneakerImageEntityDeletedAt';
import type { SneakerEntity } from './sneakerEntity';
import type { SneakerImageEntityUpdatedAt } from './sneakerImageEntityUpdatedAt';

export interface SneakerImageEntity {
  _id?: number;
  createdAt?: SneakerImageEntityCreatedAt;
  deletedAt?: SneakerImageEntityDeletedAt;
  imageUrl?: string;
  sneaker?: SneakerEntity;
  sneakerId?: number;
  updatedAt?: SneakerImageEntityUpdatedAt;
}
