/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * thecube
 * Platform API
 * OpenAPI spec version: 1.0.0
 */
import type { AccessTokenExpires } from './accessTokenExpires';

export interface AccessToken {
  expires: AccessTokenExpires;
  token: string;
}
