/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * thecube
 * Platform API
 * OpenAPI spec version: 1.0.0
 */
import type { SneakerEntity } from './sneakerEntity';

export interface Brand {
  description?: string;
  name?: string;
  sneakers?: SneakerEntity[];
}
