/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * thecube
 * Platform API
 * OpenAPI spec version: 1.0.0
 */
import type { BrandEnitiyCreatedAt } from './brandEnitiyCreatedAt';
import type { BrandEnitiyDeletedAt } from './brandEnitiyDeletedAt';
import type { SneakerEntity } from './sneakerEntity';
import type { BrandEnitiyUpdatedAt } from './brandEnitiyUpdatedAt';

export interface BrandEnitiy {
  _id?: number;
  createdAt?: BrandEnitiyCreatedAt;
  deletedAt?: BrandEnitiyDeletedAt;
  description?: string;
  name?: string;
  sneakers?: SneakerEntity[];
  updatedAt?: BrandEnitiyUpdatedAt;
}
