/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * thecube
 * Platform API
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryEntityCreatedAt } from './categoryEntityCreatedAt';
import type { CategoryEntityDeletedAt } from './categoryEntityDeletedAt';
import type { CategoryEntityUpdatedAt } from './categoryEntityUpdatedAt';

export interface CategoryEntity {
  _id?: number;
  createdAt?: CategoryEntityCreatedAt;
  deletedAt?: CategoryEntityDeletedAt;
  name?: string;
  sneakerIds?: number[];
  updatedAt?: CategoryEntityUpdatedAt;
}
