/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * thecube
 * Platform API
 * OpenAPI spec version: 1.0.0
 */
import type { GenericTokenEntityCreatedAt } from './genericTokenEntityCreatedAt';
import type { GenericTokenEntityDeletedAt } from './genericTokenEntityDeletedAt';
import type { GenericTokenEntityExpiry } from './genericTokenEntityExpiry';
import type { GenericTokenEntityUpdatedAt } from './genericTokenEntityUpdatedAt';

export interface GenericTokenEntity {
  _id?: number;
  createdAt?: GenericTokenEntityCreatedAt;
  deletedAt?: GenericTokenEntityDeletedAt;
  expiry?: GenericTokenEntityExpiry;
  meta?: unknown;
  token?: string;
  tokenType?: unknown;
  updatedAt?: GenericTokenEntityUpdatedAt;
  user?: unknown;
  userEmail?: string;
  userId?: number;
}
