/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * thecube
 * Platform API
 * OpenAPI spec version: 1.0.0
 */

export type GetByQueryCategoryParams = {
select?: unknown;
relations?: unknown;
where?: unknown;
order?: unknown;
skip?: number;
take?: number;
cache?: boolean;
};
