/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * thecube
 * Platform API
 * OpenAPI spec version: 1.0.0
 */

export type MixedClassType = typeof MixedClassType[keyof typeof MixedClassType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MixedClassType = {
  ADMIN: 'ADMIN',
  CUSTOMER: 'CUSTOMER',
  GUEST: 'GUEST',
} as const;
