/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * thecube
 * Platform API
 * OpenAPI spec version: 1.0.0
 */

export interface QueryOptions {
  cache?: boolean;
  order?: unknown;
  relations?: unknown;
  select?: unknown;
  skip?: number;
  take?: number;
  where?: unknown;
}
