/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * thecube
 * Platform API
 * OpenAPI spec version: 1.0.0
 */
import type { SneakerEntity } from './sneakerEntity';

export interface SneakerImage {
  imageUrl?: string;
  sneaker?: SneakerEntity;
  sneakerId?: number;
}
