/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * thecube
 * Platform API
 * OpenAPI spec version: 1.0.0
 */
import type { BrandEnitiy } from './brandEnitiy';
import type { SneakerColour } from './sneakerColour';
import type { SneakerReleaseDate } from './sneakerReleaseDate';
import type { SneakerImageEntity } from './sneakerImageEntity';

export interface Sneaker {
  brand?: BrandEnitiy;
  brandId?: number;
  categoryIds?: number[];
  colour?: SneakerColour;
  description?: string;
  name?: string;
  releaseDate?: SneakerReleaseDate;
  sneakerImages?: SneakerImageEntity[];
}
