/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * thecube
 * Platform API
 * OpenAPI spec version: 1.0.0
 */

export type UserEntityType = typeof UserEntityType[keyof typeof UserEntityType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserEntityType = {
  ADMIN: 'ADMIN',
  CUSTOMER: 'CUSTOMER',
  GUEST: 'GUEST',
} as const;
