/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * thecube
 * Platform API
 * OpenAPI spec version: 1.0.0
 */

export type UserEntityTitle = typeof UserEntityTitle[keyof typeof UserEntityTitle];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserEntityTitle = {
  Mr: 'Mr',
  Mrs: 'Mrs',
  Miss: 'Miss',
  Ms: 'Ms',
  Dr: 'Dr',
  Prof: 'Prof',
} as const;
