/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * thecube
 * Platform API
 * OpenAPI spec version: 1.0.0
 */
import type { UserEntityCreatedAt } from './userEntityCreatedAt';
import type { UserEntityDeletedAt } from './userEntityDeletedAt';
import type { UserEntityTitle } from './userEntityTitle';
import type { GenericTokenEntity } from './genericTokenEntity';
import type { UserEntityType } from './userEntityType';
import type { UserEntityUpdatedAt } from './userEntityUpdatedAt';

export interface UserEntity {
  _id?: number;
  createdAt?: UserEntityCreatedAt;
  deletedAt?: UserEntityDeletedAt;
  dob?: unknown;
  email?: string;
  firstName?: string;
  lastName?: string;
  password?: string;
  phoneNumber?: string;
  title?: UserEntityTitle;
  tokens?: GenericTokenEntity[];
  type?: UserEntityType;
  updatedAt?: UserEntityUpdatedAt;
}
